exports.login = async (req, res) => {
  try {
  } catch (e) {
    res.status(500).json({ error: 'something went wrong!' })
  }
}

exports.signin = async (req, res) => {
  try {
  } catch (e) {
    res.status(500).json({ error: 'something went wrong!' })
  }
}

exports.logout = async (req, res) => {
  try {
  } catch (e) {
    res.status(500).json({ error: 'something went wrong!' })
  }
}
